# Generated by Django 2.0.2 on 2018-02-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='desiredSal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
