# Generated by Django 2.0.2 on 2018-02-20 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180220_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='company',
            new_name='id_Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='sphere',
            new_name='id_Sphere',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='experience',
            new_name='exp',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='patronymic_person',
            new_name='patronymic_Person',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='person',
            new_name='id_Person',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='sphere',
            new_name='id_Sphere',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='subdivision',
            new_name='id_Subdivision',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='branch',
            new_name='id_Branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='info',
            field=models.CharField(default='Person', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 8, 43, 37, 789347, tzinfo=utc)),
        ),
    ]
